"""Canonical GreenOS secret names used by runtime secret providers."""

from __future__ import annotations


SECRET_GREENOS_SIGNING_SECRET = "GREENOS_SIGNING_SECRET"
SECRET_GREENOS_SIGNING_ACTIVE_KEY_VERSION = "GREENOS_SIGNING_ACTIVE_KEY_VERSION"
SECRET_GREENOS_SIGNING_KEYS_JSON = "GREENOS_SIGNING_KEYS_JSON"

SECRET_GREENOS_ED25519_PRIVATE_KEY = "GREENOS_ED25519_PRIVATE_KEY"
SECRET_GREENOS_ED25519_PUBLIC_KEY = "GREENOS_ED25519_PUBLIC_KEY"
SECRET_GREENOS_ED25519_ACTIVE_KEY_VERSION = "GREENOS_ED25519_ACTIVE_KEY_VERSION"
SECRET_GREENOS_ED25519_PRIVATE_KEYS_JSON = "GREENOS_ED25519_PRIVATE_KEYS_JSON"
SECRET_GREENOS_ED25519_PUBLIC_KEYS_JSON = "GREENOS_ED25519_PUBLIC_KEYS_JSON"

GREENOS_REQUIRED_SIGNING_SECRETS = (
    SECRET_GREENOS_SIGNING_SECRET,
    SECRET_GREENOS_SIGNING_ACTIVE_KEY_VERSION,
    SECRET_GREENOS_SIGNING_KEYS_JSON,
    SECRET_GREENOS_ED25519_PRIVATE_KEY,
    SECRET_GREENOS_ED25519_PUBLIC_KEY,
    SECRET_GREENOS_ED25519_ACTIVE_KEY_VERSION,
    SECRET_GREENOS_ED25519_PRIVATE_KEYS_JSON,
    SECRET_GREENOS_ED25519_PUBLIC_KEYS_JSON,
)

ENV_NAME_TO_SETTINGS_ATTR = {
    SECRET_GREENOS_SIGNING_SECRET: "greenos_signing_secret",
    SECRET_GREENOS_SIGNING_ACTIVE_KEY_VERSION: "greenos_signing_active_key_version",
    SECRET_GREENOS_SIGNING_KEYS_JSON: "greenos_signing_keys_json",
    SECRET_GREENOS_ED25519_PRIVATE_KEY: "greenos_ed25519_private_key",
    SECRET_GREENOS_ED25519_PUBLIC_KEY: "greenos_ed25519_public_key",
    SECRET_GREENOS_ED25519_ACTIVE_KEY_VERSION: "greenos_ed25519_active_key_version",
    SECRET_GREENOS_ED25519_PRIVATE_KEYS_JSON: "greenos_ed25519_private_keys_json",
    SECRET_GREENOS_ED25519_PUBLIC_KEYS_JSON: "greenos_ed25519_public_keys_json",
}

